name: Build FFmpeg on push
on:
  push:
    paths:
      - .github/workflows/build-on-push.yaml
  
jobs:
  build:
    name: Build FFmpeg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          windows-x86_64,
          ubuntu-x86_64
        ]
        include:
          - name: windows-x86_64
            os: windows-2019
            shell: 'msys2 {0}'
          - name: ubuntu-x86_64
            os: ubuntu-20.04
            shell: bash
    defaults:
      run:
        shell: ${{ matrix.shell }}
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Using msys2
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2

      # - name: Build x264
      #   working-directory: vobuild
      #   run: ./build.sh -t x264

      # - name: Build x265
      #   working-directory: vobuild
      #   run: ./build.sh -t x265

      - name: Build vmaf
        working-directory: vobuild
        run: ./build.sh -t vmaf

      # - name: Build eagle
      #   working-directory: vobuild
      #   run: ./build.sh -t eagle

      - name: Prepare Artifacts
        run: |
          mv vobuild/install ffmpeg-${{ matrix.name }}
          tar -czvf ffmpeg-${{ matrix.name }}.tar.gz ffmpeg-${{ matrix.name }}/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.name }}
          path: ffmpeg-${{ matrix.name }}.tar.gz

  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download windows-x86_64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-windows-x86_64

      - name: Download ubuntu-x86_64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-ubuntu-x86_64

      - name: Release
        run: |
          gh release create ${GITHUB_REF#refs/*/} \
          -t ${GITHUB_REF#refs/*/} \
          -F RELEASE_NOTES \
          "ffmpeg-windows-x86_64.tar.gz" \
          "ffmpeg-ubuntu-x86_64.tar.gz"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
