name: Build FFmpeg on push
on:
  push:
    paths:
      - .github/workflows/build-on-push.yaml
  
jobs:
  build:
    name: Build FFmpeg
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [windows-win64, ubuntu_focal-amd64]
        os: [windows-2019, ubuntu-20.04]
    env:
      CC: gcc
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build x264
        working-directory: vobuild
        run: ./build.sh -t x264

      - name: Build x265
        working-directory: vobuild
        run: ./build.sh -t x265

      - name: Build vmaf
        working-directory: vobuild
        run: ./build.sh -t vmaf

      - name: Build eagle
        working-directory: vobuild
        run: ./build.sh -t eagle

      - name: Prepare Asset
        working-directory: vobuild
        run: tar -czvf ffmpeg-${{ matrix.name }}.tar.gz install/
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ffmpeg-${{ matrix.name }}
          path: ffmpeg-${{ matrix.name }}.tar.gz

    outputs:
      date-time-before: ${{ steps.date-time-before.outputs.date-time }}
      date-time-after: ${{ steps.date-time-after.outputs.date-time }}
      date-time-after-tag: ${{ steps.date-time-after.outputs.date-time-tag }}
      helper-git-sha: ${{ steps.helper-git-sha.outputs.git-sha }}
  publish:
    name: Publish Release
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Download windows-win64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-windows-win64
          path: ffmpeg-windows-win64.tar.gz

      - name: Download ubuntu_focal-amd64 Artifacts
        uses: actions/download-artifact@v3
        with:
          name: ffmpeg-ubuntu_focal-amd64
          path: ffmpeg-ubuntu_focal-amd64.tar.gz

      - name: Release
        run: |
          gh release create "m-${{ needs.build.outputs.date-time-after-tag }}" \
          "ffmpeg-windows-win64.tar.gz" \
          "ffmpeg-ubuntu_focal-amd64.tar.gz" \
          -n "FFmpeg git-${{ needs.build.outputs.git-sha }} in ${{ needs.build.outputs.git-date }} built on ${{ needs.build.outputs.date-time-after }} started at ${{ needs.build.outputs.date-time-before }}
          Using ffmpeg-windows-build-helpers git-${{ needs.build.outputs.helper-git-sha }}" \
          -t "${{ needs.build.outputs.date-time-after }} ${{ needs.build.outputs.git-sha }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}